
<table>
    <tr>
      <td>Grado en Ingeniería de Datos e Inteligencia Artificial - Facultad de Informática - UCM
      </td>
      <td>
      <img src="https://biblioteca.ucm.es/data/cont/media/www/pag-88746//escudo.jpg"  width=50/>
      </td>
     </tr>
</table>

## Adquisicion y preprocesamiento de datos

<img src="https://numpy.org/doc/stable/_static/numpylogo.svg"/>

# La velocidad: una razón para usar numpy
Numpy representa vectores y matrices de forma más eficiente; va a ser el soporte de los dataframes en Pandas. Veamos distintas formas de encontrar el máximo de un vector


In [3]:
%%time
import random
cuantos = 10000000
l = [random.randint(1,100) for n in range(cuantos)]

CPU times: total: 3.31 s
Wall time: 3.31 s


In [4]:
%%time
maximo = 0
for x in l:
    if x>maximo:
        maximo=x
print(maximo)        
        


100
CPU times: total: 375 ms
Wall time: 376 ms


In [5]:
%%time 
max(l)

CPU times: total: 78.1 ms
Wall time: 77.7 ms


100

Ahora con numpy

In [6]:
%%time
import numpy as np
l =  np.random.randint(1, 100, cuantos)

CPU times: total: 172 ms
Wall time: 870 ms


In [7]:
%%time
import numpy as np
l.max()

CPU times: total: 0 ns
Wall time: 1.88 ms


np.int32(99)

# Creación de ndarrays

#### Creación desde arrays Python

In [8]:
import numpy as np
v = [10,20,30,40]
a1  = np.array(v) 

print(a1, a1.shape, a1.dtype)

[10 20 30 40] (4,) int64


In [9]:
v = [10,20,30,40,"hola"]
a1  = np.array(v) 

print(a1, a1.shape, a1.dtype)

['10' '20' '30' '40' 'hola'] (5,) <U21


En https://numpy.org/doc/stable/reference/arrays.dtypes.html hay algunas explicaciones sobre los tipos de datos de numpy

In [10]:
d = [[1, 2, 3, 4], [5, 6, 7, 8.2]]

a2 = np.array(d)
print(a2, a2.shape, a2.dtype)

[[1.  2.  3.  4. ]
 [5.  6.  7.  8.2]] (2, 4) float64


Es importante notar que *array* crea una copia, esto es, reserva memoria nueva para el resultado.
La variante *asarray* no crea una copia si el parámetro ya es un *ndarray*

In [11]:

d = [[1, 2, 3, 4], [5, 6, 7, 8.2]]

a2 = np.array(d)
a3 = np.array(a2)
a4 = np.asarray(a2)

a3[0,1] = 0
a4[1,3] = 0 #modifica a2 tambien 
print(a2)
print(a3)
print(a4)

[[1. 2. 3. 4.]
 [5. 6. 7. 0.]]
[[1.  0.  3.  4. ]
 [5.  6.  7.  8.2]]
[[1. 2. 3. 4.]
 [5. 6. 7. 0.]]


### Crear arrays en numpy repitiendo valores

Aparte de *np.array* tenemos:

- *np.zeros(s)*: crea un array con 0s (float) con el *shape* indicado<br>

- *np.zeros_like(a)*: crea un array con 0s (float) con el mismo *shape* que el del array *a*<br>

- *np.ones(s)*: crea un array con 1s (float) con el *shape* indicado<br>

- *np.ones_like(a)*: crea un array con 1s (float) con el mismo *shape* que el del array *a*<br>

- *np.empty(s)*: crea un array con el *shape* indicado sin inicializar<br>

- *np.empty_like(a)*: crea un array con el *shape* de *a* sin inicializar<br>

- *np.arange(n)*: la versión np de *range*

- *np.eye(n)*, *np.identity(n)*: matriz diagonal de nxn

In [12]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Crear arrays en numpy mediante números aleatorios

numpy dispone de un paquete `numpy.random` que se encarga de generar números aleatrorios. Python también dispone de dicho paquete. La diferencia es que el módulo de numpy puede generar muchos valores diferentes con una sola llamada y de muy diversas funciones de probabilidad. 

Las funciones incluídas en este paquete son: 

    seed: semilla del generador de números aleatorios
    permutation: permutación al azar de una secuencia
    shuffle: permuta una secuencia in-place (no devuelve copia)
    rand: devuelve números aleatorios de una función uniforme
    randint: Valores enteros distribuidos uniformemente 
    randn: valores de una N(0,1)
    binomial: ejemplo de una binomial
    normal: valores de una gaussiana cuyos parámetros se le pasan
    beta: valores aleatorios de una distribución beta
    chisquare: valores aleatorios de una chi-cuadrado
    gamma: valores de una gamma
    uniform: valores de una uniforme (0,1)
    
Vamos a comparar en velocidad con la generación mediante números aleatorios de Python

In [13]:
from random import normalvariate 
N = 1000000
%timeit [normalvariate(0,1) for _ in range(N)]

380 ms ± 4.02 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
import numpy as np
%timeit np.random.normal(size=N)

20.2 ms ± 847 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Al usar timeit se puede especificar el número de repeticiones (r) y de iteraciones (n)

In [15]:
%timeit -n 100 -r 5 np.random.normal(size=N)

20.6 ms ± 616 μs per loop (mean ± std. dev. of 5 runs, 100 loops each)


# 📊 Funciones Estadísticas en NumPy
#### Principales funciones estadísticas de NumPy


NumPy proporciona un conjunto de funciones estadísticas optimizadas para el análisis de datos. Estas funciones permiten calcular **medidas de tendencia central, dispersión, percentiles y correlaciones** de manera eficiente sobre arrays de cualquier tamaño.

**Medidas de Tendencia Central**: Estas funciones permiten calcular valores representativos de un conjunto de datos:

- **mean**: Calcula la media aritmética de los elementos del array.
- **median**: Obtiene la mediana del conjunto de datos, es decir, el valor central.
- **mode**: Determina el valor más frecuente en los datos (*no está en NumPy directamente, pero se puede calcular con SciPy*).

**Medidas de Dispersión**:
Las medidas de dispersión describen cómo varían los datos con respecto a su media:

- **std**: Calcula la desviación estándar, que mide la dispersión de los datos.
- **var**: Calcula la varianza, que es la desviación estándar elevada al cuadrado.
- **ptp**: Devuelve el rango de los datos, es decir, la diferencia entre el valor máximo y mínimo.

**Percentiles y Cuantiles**:
Los percentiles dividen los datos en segmentos según su orden. Algunas funciones útiles incluyen:

- **percentile**: Calcula el percentil especificado dentro del conjunto de datos.
- **quantile**: Generaliza los percentiles, permitiendo calcular cuartiles, deciles, etc.

**Mínimos, Máximos y Suma**:
NumPy permite obtener información sobre los valores extremos y la suma de los elementos:

- **min**: Devuelve el valor mínimo del array.
- **max**: Devuelve el valor máximo del array.
- **sum**: Calcula la suma total de todos los elementos del array.

**Medidas de Correlación y Covarianza**:
Para analizar la relación entre diferentes conjuntos de datos, NumPy incluye funciones como:

- **corrcoef**: Calcula la matriz de correlación de Pearson entre dos variables.
- **cov**: Calcula la matriz de covarianza, que mide cómo varían dos variables conjuntamente.

**Conteo de Frecuencias**:
NumPy permite contar la frecuencia de valores en un conjunto de datos:

- **unique**: Devuelve los valores únicos en un array.
- **bincount**: Cuenta la frecuencia de ocurrencia de valores enteros en un array.


In [16]:
import numpy as np

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# 1. Medidas de Tendencia Central
mean_value = np.mean(data)  # Media
median_value = np.median(data)  # Mediana

# 2. Medidas de Dispersión
std_dev = np.std(data)  # Desviación estándar
variance = np.var(data)  # Varianza
range_value = np.ptp(data)  # Rango (máx - mín)

# 3. Percentiles y Cuantiles
percentile_25 = np.percentile(data, 25)  # Percentil 25
percentile_50 = np.percentile(data, 50)  # Percentil 50 (Mediana)
percentile_75 = np.percentile(data, 75)  # Percentil 75

# 4. Mínimos, Máximos y Suma
min_value = np.min(data)  # Valor mínimo
max_value = np.max(data)  # Valor máximo
sum_value = np.sum(data)  # Suma total

# 5. Medidas de Correlación y Covarianza
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
correlation = np.corrcoef(x, y)  # Matriz de correlación
covariance = np.cov(x, y)  # Matriz de covarianza

# 6. Conteo de Frecuencias
values = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_values, counts = np.unique(values, return_counts=True)  # Valores únicos y sus frecuencias
bincounts = np.bincount(values)  # Conteo de ocurrencias de enteros

# Mostrar resultados
print(" Resultados de Estadísticas con NumPy\n")
print(f"Media: {mean_value:.2f}")
print(f"Mediana: {median_value:.2f}")
print(f"Desviación estándar: {std_dev:.2f}")
print(f"Varianza: {variance:.2f}")
print(f"Rango: {range_value}")

print(f"\nPercentil 25: {percentile_25}")
print(f"Percentil 50 (Mediana): {percentile_50}")
print(f"Percentil 75: {percentile_75}")

print(f"\nValor mínimo: {min_value}")
print(f"Valor máximo: {max_value}")
print(f"Suma total: {sum_value}")

print(f"\nCoeficiente de correlación:\n{correlation}")
print(f"Matriz de covarianza:\n{covariance}")

print(f"\nValores únicos: {unique_values}")
print(f"Frecuencia de valores únicos: {counts}")
print(f"Conteo de frecuencia (bincount): {bincounts}")


 Resultados de Estadísticas con NumPy

Media: 55.00
Mediana: 55.00
Desviación estándar: 28.72
Varianza: 825.00
Rango: 90

Percentil 25: 32.5
Percentil 50 (Mediana): 55.0
Percentil 75: 77.5

Valor mínimo: 10
Valor máximo: 100
Suma total: 550

Coeficiente de correlación:
[[1. 1.]
 [1. 1.]]
Matriz de covarianza:
[[ 2.5  5. ]
 [ 5.  10. ]]

Valores únicos: [1 2 3 4]
Frecuencia de valores únicos: [1 2 3 4]
Conteo de frecuencia (bincount): [0 1 2 3 4]


# 📈 Vectorización
#### Operaciones vectoriales

Aparte de la velocidad y de la gran cantidad de funciones que contiene, la *vectorización* es una razón importante para utilizar numpy. La idea es sí es muy sencilla:



Vectorización *Toda operación que se pueda aplicar a un elemento de un tipo básico (ej. int) se extiende forma natural a ndarrays*

In [17]:
a = 20
b = 30
a+b   # python puro

50

In [18]:
import numpy as np

a  = np.array([10,20,30,40]) 
b  = np.array([100,200,300,400])

a+b # numpy

array([110, 220, 330, 440])

In [19]:
a*b 

array([ 1000,  4000,  9000, 16000])

In [20]:
(a+b)/2

array([ 55., 110., 165., 220.])

### Broadcasting

Para poder operar entre dos vectores éstos tienen que ser en principio de la misma longitud. Sin embargo, siempre que pueda, al detectar diferencias de tamaño numpy "repetirá" elementos para lograr que encajen ambos operandos. Esto se conoce como "broadcasting"

In [21]:
m = np.zeros((10,10),dtype=np.int32)
m

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [22]:
m[3:7,3:7]=1
m

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [23]:
m + 2

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 3, 3, 3, 3, 2, 2, 2],
       [2, 2, 2, 3, 3, 3, 3, 2, 2, 2],
       [2, 2, 2, 3, 3, 3, 3, 2, 2, 2],
       [2, 2, 2, 3, 3, 3, 3, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int32)

## Índices booleanos

Todavía una razón más; utilizar arrays de booleanos como índices; esto va a ser una herramienta muy poderosa para filtrar datos

In [24]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a[ [True,False,False,True,False,False,True,False,False,False]]

array([1, 4, 7])

Esto, que parece no tener importancia, muestra su potencia al combinarlo con la vectorización, y da lugar a todo un estilo de programación

In [26]:
a % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [27]:
filtro = a % 2 == 0
a[filtro]

array([ 2,  4,  6,  8, 10])

In [28]:
a[ a % 2 == 0]

array([ 2,  4,  6,  8, 10])

**Ejemplo**
Queremos quedarnos solo con los elementos positivos del array a

In [29]:
a = np.random.randint(-100,100,50)
a

array([ 43,  -1,  31, -89,  88,  33, -93,  81,  20, -58,  -9, -27, -16,
        86,  62,  12, -60,  98,  84,  -6, -31, -47,  94, -79, -98,  70,
        92, -89, -54,  10, -98,  64, -41, -98,  69,  50,   8, -86, -56,
        79, -70, -57,  53, -83,  38,  85, -56, -67,  71,   3], dtype=int32)

In [30]:
# solución


Se pueden combinar dos arrays

In [31]:
nombre = np.array(["Bertoldo","Herminia","Calixto","Melibea","Aniceto"])
ingresos = np.array([1200,800,1500,2300,940])

nombre, ingresos

(array(['Bertoldo', 'Herminia', 'Calixto', 'Melibea', 'Aniceto'],
       dtype='<U8'),
 array([1200,  800, 1500, 2300,  940]))

In [32]:
# Nombre de los que ganan más de 1000 euros
filtro = ingresos>1000
nombre[filtro]

array(['Bertoldo', 'Calixto', 'Melibea'], dtype='<U8')

### **Ejercicio** A partir de la listas `edades` y `nombres` queremos crear 4 listas: `edades20`, `nombres20` con las edades menores o iguales a 20 y sus nombres, y `edadesMasDe20`, `nombresMasDe20` con las edades y nombres de los que tienen más de 20 años

In [33]:
nombres = np.array(["Melibea", "Bertoldo", "Herminia", "Calixto", "Aniceto"])
edades = np.array([18,20,23,18,21])

Sobre los arrays booleanos se pueden hacer operaciones and (se escribe &), or (|) y not (~)

In [34]:
filtro1

NameError: name 'filtro1' is not defined

In [ ]:
~filtro1

array([ True,  True, False,  True, False])

In [ ]:
filtro = edades>20


edades20, nombres20  = edades[~filtro], nombres[~filtro]

edadesMasDe20, nombresMasDe20 = edades[filtro], nombres[filtro]

print(edades20, nombres20)
print(edadesMasDe20, nombresMasDe20 )

[18 20 18] ['Melibea' 'Bertoldo' 'Calixto']
[23 21] ['Herminia' 'Aniceto']


*En general en ciencia de datos en Python evitaremos los bucles `for` siempre que sea posible, las bibliotecas como numpy ofrecen alternativas más elegantes y mucho más rápidas*

### Ejercicio: Se tiene un array de NumPy que representa las **notas finales** de 20 estudiantes en una escala de 0 a 100. 

Realiza las siguientes tareas:

1. **Calcular las estadísticas básicas** del conjunto de notas:
   - Media
   - Mediana
   - Desviación estándar
   - Nota máxima y mínima

2. **Determinar los estudiantes aprobados y suspensos**:
   - Se considera **aprobado** si la nota es **≥ 50**.
   - Calcular el **porcentaje de estudiantes aprobados**.

3. **Escalar las notas a una escala de 0 a 10**:
   - Convertir las notas del rango **0-100** a **0-10**.

4. **Aplicar una curva de mejora**:
   - Si la media de la clase es **menor a 60**, aumentar todas las notas en **10%**, sin que ninguna supere el valor de **100**.

5. **Mostrar los resultados** en pantalla.

In [ ]:
import numpy as np

# Array con notas aleatorias de 20 estudiantes (escala 0-100)
np.random.seed(42)  # Semilla
notas = np.random.randint(30, 100, size=20)  # Notas entre 30 y 100

#solución


Notas: [81 44 90 50 53 32 51 82 31 59 67 31 93 89 50 62 87 51 78 88]
Media: 63.45, Mediana: 60.50, Desviación estándar: 20.67
Nota máxima: 93, Nota mínima: 31
Estudiantes aprobados: 16 (80.00%)
Estudiantes reprobados: 4
Notas en escala 0-10: [8.1 4.4 9.  5.  5.3 3.2 5.1 8.2 3.1 5.9 6.7 3.1 9.3 8.9 5.  6.2 8.7 5.1
 7.8 8.8]
No se aplica curva de mejora.
